apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-default-volume"
spec:
  capacity:
    # the required allocated storage
    storage: "8Gi"
  accessModes:
    - "ReadWriteMany"
  glusterfs:
    endpoints: "glusterfs-cluster"
    # the name of the gluster volume, as configured in gluster
    path: "kubernetes"
    readOnly: false
  persistentVolumeReclaimPolicy: "Recycle"
